In [1]:
import torch
import torch.nn.functional as F


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vicentearjona/Documents/Spelled-out intro to Lang Models/.venv/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.l

In [2]:
words = open('names.txt', 'r').read().splitlines()

abc = ['*'] + sorted(list(set(''.join(words))))
stoi = {ch: ix for ix, ch in enumerate(abc)}
itos = {ix: ch for ch, ix in stoi.items()}

In [3]:
X, Y = [], []
for w in words[:5]:
    print(w)
    context = [0] * 3 
    for ch in w + '*': 
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        #print(''.join(itos[i] for i in context), ch)
        #print(X, Y)
        context = context[1:] + [ix]


emma
olivia
ava
isabella
sophia


In [4]:
X = torch.tensor(X)
Y = torch.tensor(Y)

In [5]:
X.shape

torch.Size([32, 3])

In [8]:
C = torch.randn((27,2))
C

tensor([[-2.4321e+00, -4.7759e-01],
        [-2.2295e+00,  3.7084e-01],
        [-8.3340e-01, -3.9321e-01],
        [ 3.1950e-01,  1.0226e+00],
        [ 5.9503e-01,  5.7760e-01],
        [-1.6458e+00, -2.2956e+00],
        [ 1.7346e+00, -9.3244e-01],
        [ 9.4001e-01,  1.9102e-03],
        [-1.3351e+00,  1.8155e-01],
        [-5.3494e-01,  6.2961e-01],
        [ 1.0462e+00, -1.5985e+00],
        [ 2.5947e-01, -8.1297e-01],
        [-8.7036e-02, -1.1656e+00],
        [-7.9856e-02,  5.8583e-02],
        [ 1.3146e+00,  4.1626e-02],
        [ 3.7327e-01,  9.8006e-01],
        [ 3.6658e-01, -2.6856e+00],
        [ 8.0019e-01, -1.0674e+00],
        [-8.7234e-01,  4.6597e-01],
        [-1.1542e+00, -1.8564e+00],
        [-1.0928e+00, -2.8593e-01],
        [-1.5171e-01, -1.9548e+00],
        [ 9.2411e-01,  4.6055e-01],
        [ 6.0683e-01, -2.1116e+00],
        [-4.7358e-01,  7.8869e-01],
        [ 4.3365e-01,  2.1126e+00],
        [-1.3969e+00,  1.3236e+00]])

In [11]:
C[torch.tensor([[4,5,6,3],[3,4,2,4], [5,6,7,5]])].shape
C[torch.tensor([[4,5,6,3]])]

tensor([[[ 0.5950,  0.5776],
         [-1.6458, -2.2956],
         [ 1.7346, -0.9324],
         [ 0.3195,  1.0226]]])

In [26]:
x = torch.randn(4,200)
W = torch.randn(200,150)
y = x @ W 
x.shape, W.shape, y.shape

(torch.Size([4, 200]), torch.Size([200, 150]), torch.Size([4, 150]))

In [28]:
x = torch.randn(4,10)
x , x.view(2,-1)

(tensor([[ 9.6611e-01,  4.9718e-01, -1.3655e+00, -4.3426e-01,  5.0099e-01,
          -9.7808e-02,  3.7528e-04,  8.9738e-01, -3.5254e-01, -3.1544e-01],
         [-5.1143e-01,  7.0744e-01,  4.4049e-01,  2.5468e+00,  1.6040e+00,
           2.4848e-02, -8.0306e-01, -3.4266e-01,  5.1453e-01, -5.2653e-02],
         [-4.9821e-01,  1.2239e-01,  1.3756e+00, -2.1027e+00,  7.3999e-01,
           9.0244e-01,  1.0211e+00,  6.3680e-01,  1.3914e+00,  7.0056e-01],
         [ 3.0548e-01,  3.8317e-02, -1.3921e-01, -6.7084e-01,  2.8791e-02,
          -6.8710e-01, -2.0891e+00, -2.2693e-01, -6.0230e-01, -3.8218e-01]]),
 tensor([[ 9.6611e-01,  4.9718e-01, -1.3655e+00, -4.3426e-01,  5.0099e-01,
          -9.7808e-02,  3.7528e-04,  8.9738e-01, -3.5254e-01, -3.1544e-01,
          -5.1143e-01,  7.0744e-01,  4.4049e-01,  2.5468e+00,  1.6040e+00,
           2.4848e-02, -8.0306e-01, -3.4266e-01,  5.1453e-01, -5.2653e-02],
         [-4.9821e-01,  1.2239e-01,  1.3756e+00, -2.1027e+00,  7.3999e-01,
           9.0244e

In [9]:
C[X[:3]].shape, C[X].shape

(torch.Size([3, 3, 2]), torch.Size([32, 3, 2]))

In [10]:
F.one_hot(X[0],num_classes=27)

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]])

In [11]:
F.one_hot(torch.tensor([4,5,6,3]), num_classes=10)

tensor([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]])

In [12]:
W = torch.randn(
            size=(10,10)
        )
W[[4,5,6,3]]

tensor([[-0.7877, -0.9716,  0.8740, -0.8367,  1.0740, -0.1368, -0.0825,  0.0135,
          1.1727,  0.0077],
        [ 1.0694, -0.0097,  0.0627, -0.8475, -0.6606, -0.8411, -1.5478,  2.0897,
         -1.4723,  1.0360],
        [-1.3463, -0.7043, -0.5255, -0.4036,  1.1908, -0.4049, -1.5789, -0.4418,
         -0.2108, -0.3303],
        [ 0.2573, -0.3365, -0.2029, -0.7362, -2.2794,  0.6758, -0.8515,  0.2658,
          1.4404, -0.1428]])

In [13]:
(F.one_hot(torch.tensor([4,5,6,3]), num_classes=10).float() @ W), (F.one_hot(torch.tensor([4,5,6,3]), num_classes=10).float() @ W).shape

(tensor([[-0.7877, -0.9716,  0.8740, -0.8367,  1.0740, -0.1368, -0.0825,  0.0135,
           1.1727,  0.0077],
         [ 1.0694, -0.0097,  0.0627, -0.8475, -0.6606, -0.8411, -1.5478,  2.0897,
          -1.4723,  1.0360],
         [-1.3463, -0.7043, -0.5255, -0.4036,  1.1908, -0.4049, -1.5789, -0.4418,
          -0.2108, -0.3303],
         [ 0.2573, -0.3365, -0.2029, -0.7362, -2.2794,  0.6758, -0.8515,  0.2658,
           1.4404, -0.1428]]),
 torch.Size([4, 10]))

In [14]:
C[X[2:4]]

tensor([[[-0.3748, -0.6993],
         [-1.7225,  0.4454],
         [-0.1263,  0.0169]],

        [[-1.7225,  0.4454],
         [-0.1263,  0.0169],
         [-0.1263,  0.0169]]])

In [15]:
torch.unbind(C[X[2:4]], dim=1)

(tensor([[-0.3748, -0.6993],
         [-1.7225,  0.4454]]),
 tensor([[-1.7225,  0.4454],
         [-0.1263,  0.0169]]),
 tensor([[-0.1263,  0.0169],
         [-0.1263,  0.0169]]))

In [16]:
emb = C[X]
mem = emb.view(-1, emb.shape[1] * emb.shape[2])
mem.shape

torch.Size([32, 6])

In [17]:
C[torch.arange(27), [1,1,0]*9]

tensor([-6.9931e-01,  3.2024e-01, -1.0842e-01, -4.0478e-02,  1.5012e+00,
        -1.7225e+00, -4.9225e-01, -3.7285e-01,  1.5640e-01, -1.7251e+00,
        -1.5346e+00,  6.9214e-01,  5.4545e-01,  1.6929e-02, -3.4209e-01,
         1.9399e+00,  1.8294e+00, -1.7588e-01, -1.3655e-02,  3.0336e+00,
        -9.1793e-01,  1.6983e+00,  1.0180e+00, -4.7934e-01, -5.4998e-01,
        -2.6867e-03, -4.8289e-01])

In [18]:
x = torch.tensor([4,5,6,2])-6
a1 = x.exp()
a2 = (x+6).exp()
a1 / a1.sum(0, keepdim=True), a2/a2.sum(0,keepdim=True)

(tensor([0.0889, 0.2418, 0.6572, 0.0120]),
 tensor([0.0889, 0.2418, 0.6572, 0.0120]))

In [19]:
a1.sum(), a2.sum()

(tensor(1.5215), tensor(613.8292))

In [1]:
from makemore import ContextNNBiagrams

test = ContextNNBiagrams(context=4)
test.open('names.txt')


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vicentearjona/Documents/Spelled-out intro to Lang Models/.venv/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.l

In [2]:
test.words

['yuheng',
 'diondre',
 'xavien',
 'jori',
 'juanluis',
 'erandi',
 'phia',
 'samatha',
 'phoenix',
 'emmelynn',
 'hollan',
 'hollis',
 'callalily',
 'adelayde',
 'josephyne',
 'weldon',
 'kayle',
 'ragnar',
 'colbie',
 'taveon',
 'aki',
 'peyten',
 'kevari',
 'joella',
 'mecca',
 'egan',
 'justyce',
 'taliyah',
 'hayley',
 'alleah',
 'kymberlynn',
 'parrish',
 'houstyn',
 'jamaya',
 'ahmod',
 'nivin',
 'milli',
 'cristiana',
 'jaimee',
 'mitchell',
 'nairah',
 'lorena',
 'gentrie',
 'torrion',
 'savian',
 'benjamine',
 'airess',
 'knute',
 'sultana',
 'danai',
 'azzan',
 'issabelle',
 'abrahim',
 'aislyn',
 'aerys',
 'malaiya',
 'kieon',
 'ayansh',
 'berklee',
 'emmakate',
 'avaneesh',
 'amenadiel',
 'renardo',
 'brekken',
 'kamry',
 'wylin',
 'trixie',
 'breslynn',
 'bianka',
 'mordchai',
 'haoyu',
 'frankie',
 'josselin',
 'saila',
 'kionna',
 'jennings',
 'arlington',
 'jupiter',
 'aleisha',
 'kemorah',
 'denisse',
 'zada',
 'kaydynce',
 'bari',
 'darya',
 'ellieanne',
 'gretel',
 

In [3]:
test.generate_train_val_test_splits(depth=-999)

In [4]:
test.xtrain.shape, test.xtest.shape, test.xval.shape, test.xtrain.shape[0]+ test.xtest.shape[0]+ test.xval.shape[0], test.generate_train_model()[0].shape[0]

(torch.Size([182516, 4]),
 torch.Size([22815, 4]),
 torch.Size([22815, 4]),
 228146,
 228146)

In [5]:
test.initialize_parameters(emb=20, w1_shape=300)

In [6]:
test.gradient_descent_train(lr=0.1, num_iter=200000, batch_size=100)

Iteration:0
Iteration:10000
Iteration:20000
Iteration:30000
Iteration:40000
Iteration:50000
Iteration:60000
Iteration:70000
Iteration:80000
Iteration:90000
Iteration:100000
Iteration:110000
Iteration:120000
Iteration:130000
Iteration:140000
Iteration:150000
Iteration:160000
Iteration:170000
Iteration:180000
Iteration:190000


In [7]:
test.xtrain.shape

torch.Size([182516, 4])

In [8]:
test.forward_pass(batch_size=test.xtrain.shape[0], xs=test.xtrain, ys=test.ytrain, minibatch=True)

tensor(2.1046, grad_fn=<NllLossBackward0>)

In [9]:
test.forward_pass(batch_size=test.xval.shape[0], xs=test.xval, ys=test.yval, minibatch=False)

dim(xtr) = torch.Size([22815, 4]). dim(ytr) = torch.Size([22815])


tensor(2.2162, grad_fn=<NllLossBackward0>)

In [12]:
test.gradient_descent_train(lr=0.05, num_iter=10000, batch_size=200)

Iteration:0


In [13]:
test.loss_train[-1]

tensor(1.9592, grad_fn=<NllLossBackward0>)

In [14]:
test.forward_pass(batch_size=0, xs=test.xval, ys=test.yval, minibatch=False)

dim(xtr) = torch.Size([22815, 4]). dim(ytr) = torch.Size([22815])


tensor(2.1188, grad_fn=<NllLossBackward0>)

In [15]:
test.generate_words(num_words=10)

'*juniel*jakari*juliyah*adiya*jirrino*cous*teze*sameia*zamilena*jededii*'

In [33]:
emb = test.C[torch.tensor([0,0,0])]
emb.view(1, -1).shape

torch.Size([1, 60])