In [1]:
from contextensor import ContextTorchTensor 

mem = ContextTorchTensor(context=10)
mem.open(file="input.txt")


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vicentearjona/Documents/LLM_practice/.venv/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()

In [2]:
mem.open(file="input.txt")

In [4]:
mem.words

['The guilt of conscience take thou for thy labour,',
 '',
 '',
 'KING EDWARD IV:',
 '',
 'With politic grave counsel; then the king',
 'Till holy church incorporate two in one.',
 "As fast lock'd up in sleep as guiltless labour",
 'Uncle, you say the queen is at your house;',
 'Stay: whence are you?',
 'Where is this viper',
 'A merriment than a vice.',
 'A second course of fight.',
 '',
 'Was brow-bound with the oak. His pupil age',
 'Canst thou demise to any child of mine?',
 'Not separated with the racking clouds,',
 '',
 '',
 'What, art thou waking?',
 '',
 'Tell me, I beseech you, which is the readiest way',
 '',
 'No; he doth but mistake the truth totally.',
 "My cabin where I lay; thrice bow'd before me,",
 'I have great hope in that; for in her youth',
 'As Angelo; even so may Angelo,',
 'That Julius Caesar was a famous man;',
 'Who told me how the poor soul did forsake',
 "'Yea,' quoth he, 'dost thou fall upon thy face?",
 "'Twas very faintly he said 'Rise;' dismiss'd me",
 '

In [1]:
import torch 
torch.randint(0, 100, (4,))


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vicentearjona/Documents/LLM_practice/.venv/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()

tensor([ 7, 19,  6, 60])

In [13]:
data = torch.randint(0, 100, (4,9))
x = data[:,:8]
y = data[:,1:9]

In [ ]:
import torch.nn as nn 
vocab_size = data.max().data.item() + 1
token_embedding = nn.Embedding(98, 98)
token_embedding.


98

In [33]:
class Biagram(nn.Module):
    def __init__(self, vocab_size): 
        super().__init__()
        self.token_cosa = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets):
        logits = self.token_cosa(idx) # B, T, C 
        return logits 



In [34]:
m = Biagram(vocab_size=vocab_size)

In [36]:
out = m(x, y)
out.shape

torch.Size([4, 8, 99])

In [12]:
from gpt import TrainingText, SetSplit, GetBatch, BiagramLanguageModel
import torch

In [ ]:
text = TrainingText(input_file=r"/Users/vicentearjona/Documents/LLM_practice/Neural_Networks/input.txt")

[20, 43, 50, 50, 53, 1, 61, 53, 56, 50, 42]

In [13]:
data = torch.tensor(text.encoder(text.text), dtype=torch.long)

In [14]:
split = SetSplit(train_size=0.75, test_size=0.15)
train, val, test = split.split(data=data)

In [17]:
batch_size = 16 
context = 10 
vocab_size = text.vocab_size

In [19]:
m = BiagramLanguageModel(vocab_size=vocab_size)    

In [24]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)
get_batch = GetBatch(batch_size=batch_size, context=context)

In [46]:
for _ in range(5000):
    xb , yb = get_batch(data=train)
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()


In [47]:
loss.item()

2.470839500427246

In [48]:
predict = m.generate(input=torch.zeros((1,1), dtype=torch.long), num_iterations=range(100))

In [49]:
text.decoder(predict[0].tolist())

'\nTon t erolloloisont whise, thirotithidod irtin\nPerengtonoug,\n\nHA:\nwapoualls id iarsteemeis ly stous;'

In [2]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

emb_size = 10
head_size= 16
context_size = 8


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vicentearjona/Documents/LLM_practice/.venv/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()

In [3]:
query = nn.Linear(in_features=emb_size, out_features=head_size, bias=False)
key = nn.Linear(in_features=emb_size, out_features=head_size, bias=False)
value = nn.Linear(in_features=emb_size, out_features=head_size, bias=False) 
tril = torch.tril(torch.ones((context_size, context_size)))

In [4]:
input = torch.rand((4,context_size, emb_size))
B,T,C = input.shape
q = query(input)   # (B,T,H)
k = key(input)     # (B,T,H)
v = value(input)   # (B,T,H)
w = q @ k.transpose(1,2) * C **-0.5    # (B,T,H) @ (B,H,T) = (B,T,T)
w = w.masked_fill(tril == 0, float('-inf'))    # (B,T,T) without speaking with the future
w = F.softmax(w, dim=2) # (B,T,T) 
out = w @ v # (B,T,T) @ (B,T,H) = (B,T,H)

In [5]:
out[0]

tensor([[-1.8018e-01, -3.7821e-01, -1.6861e-01,  3.1565e-01, -6.7192e-01,
          4.6068e-01,  6.1322e-01, -2.1963e-01, -1.7687e-01, -3.4673e-01,
          6.7052e-02,  1.6443e-01,  1.1984e-01,  5.9880e-01, -1.6896e-01,
         -1.1622e-01],
        [-2.6411e-01, -4.1405e-01, -2.0997e-01,  3.1962e-01, -6.5203e-01,
          4.0382e-01,  5.4416e-01, -2.7847e-01, -1.6809e-01, -3.4954e-01,
         -4.2795e-02,  9.1103e-02,  1.2993e-01,  5.8649e-01, -7.5014e-02,
         -9.5670e-02],
        [-2.8351e-01, -4.1393e-01, -2.1251e-01,  2.8649e-01, -6.0919e-01,
          3.6975e-01,  5.0537e-01, -3.5004e-01, -1.5710e-01, -2.8779e-01,
         -2.6039e-02,  1.0139e-01,  1.4975e-01,  5.5790e-01, -1.0647e-02,
         -1.1659e-01],
        [-2.8992e-01, -3.9879e-01, -1.9701e-01,  2.4905e-01, -5.8830e-01,
          3.7924e-01,  4.9378e-01, -3.8143e-01, -1.7502e-01, -3.0980e-01,
         -5.5445e-02,  7.3387e-02,  1.2987e-01,  5.4805e-01,  6.9752e-03,
         -5.8037e-02],
        [-2.6251e-01

In [9]:
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a[-5:]

tensor([5, 6, 7, 8, 9])

In [11]:
from gpt import Head
h = Head(context_size=10, emb_size=16, head_size=16)

In [12]:
a = a[-5:]

In [14]:
a = torch.rand((1,1,16))

In [18]:
q = h.query(a) 
k = h.key(a) 
v = h.value(a)

In [37]:
q.shape, k.shape, v.shape

(torch.Size([1, 1, 16]), torch.Size([1, 1, 16]), torch.Size([1, 1, 16]))

In [40]:
w = q @ k.transpose(1,2)
w.shape

torch.Size([1, 1, 1])

In [41]:
B, T, C = a.shape 
w = w.masked_fill(tril[:T, :T] == 0, float('-inf'))
out = w @ v

In [43]:
w.shape , v.shape

(torch.Size([1, 1, 1]), torch.Size([1, 1, 16]))

In [44]:
v, k

(tensor([[[-0.9547, -0.1961, -0.1279, -0.4571, -0.0543,  0.2940, -0.1942,
            0.1608, -0.1116, -0.1061, -0.4020,  0.3327,  0.0722,  0.0902,
           -0.2079, -0.1277]]], grad_fn=<UnsafeViewBackward0>),
 tensor([[[ 0.4987, -0.0543,  0.4169,  0.1034, -0.0341,  0.2122,  0.2045,
            0.3549, -0.5250, -0.2587, -0.2326,  0.1236,  0.2765,  0.1412,
           -0.0326, -0.2836]]], grad_fn=<UnsafeViewBackward0>))

In [48]:
torch.cat((v,k)).shape

torch.Size([2, 1, 16])

## Issue with shapes 

In [1]:
import torch
from gpt import (
    TrainingText,
    SetSplit,
    BiagramLanguageModel,
    SingleHeadBiagramLanguageModel,
    MultiHeadBiagramLanguageModel,
    GetBatch,
    EstimateLoss,
)

# Get training text. Generate decoder/encoder and vocab paramenters
file = TrainingText(
    input_file=r"/Users/vicentearjona/Documents/LLM_practice/Neural_Networks/input.txt"
)
# Parameters
vocab_size = file.vocab_size
context_size = 16
batch_size = 16
max_iters = 10000
eval_interval = 300
eval_iters = 200
learning_rate = 1e-3
head_size = 64
head_dim = 8
emb_size = 64
device = "cuda" if torch.cuda.is_available() else "cpu"
# Set seed
torch.manual_seed(1337)
# Transform into torch tensor
data = torch.tensor(file.encoder(file.text), dtype=torch.long)
# Get train / val / test splits
splitter = SetSplit(train_size=0.75, test_size=0.15)
train, val, test = splitter.split(data=data)
# Define the object to split the data into batches
get_batch = GetBatch(batch_size=batch_size, context=context_size, device=device)
xb, yb = get_batch(data=train)  # get batches


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vicentearjona/Documents/LLM_practice/.venv/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()

In [2]:
xb.shape

torch.Size([16, 16])

In [3]:
import torch.nn as nn 
import torch 

In [4]:
token_emb_table = nn.Embedding(
            num_embeddings=vocab_size, embedding_dim=emb_size
        )
position_emb_table = nn.Embedding(
            num_embeddings=context_size, embedding_dim=emb_size
        )

In [9]:
B, T = xb.shape 
tk_emb = token_emb_table(xb)
ps_emb = position_emb_table(torch.arange(T))
x = tk_emb + ps_emb

In [6]:
from gpt import FeedForward, MultiHead

heads = MultiHead(context_size, emb_size, head_size, head_dim)
ff = FeedForward(ff_size=head_size)

In [7]:
x = heads(x)

torch.Size([16, 16, 512])
torch.Size([16, 16, 512])


In [10]:
x.shape

torch.Size([16, 16, 64])

In [11]:
from gpt import Block

blockade = Block(context_size=context_size, emb_size=emb_size, head_size=head_size, head_dim=head_dim, ff_size=head_size)

In [13]:
out = blockade(x)

x shape = torch.Size([16, 16, 64])
torch.Size([16, 16, 64])
torch.Size([16, 16, 64])
heads shape = torch.Size([16, 16, 64])
ff shape = torch.Size([16, 16, 64])
torch.Size([16, 16, 64])
torch.Size([16, 16, 64])


In [14]:
out.shape

torch.Size([16, 16, 64])

In [2]:
def kk(arg1, arg2, arg3, arg4): 
    print(f'1:{arg1}') 
    print(f'2:{arg2}') 
    print(f'3:{arg3}') 
    print(f'4:{arg4}') 
    
kk(*[1,3,4,5])

1:1
2:3
3:4
4:5
